klogcat: cleanup
Signed-off-by: Fudong Bai <fudongbai@gmail.com>

diff --git a/android/script/klogcat b/android/script/klogcat
--- a/android/script/klogcat
+++ b/android/script/klogcat
@@ -1,17 +1,10 @@
 #!/system/bin/sh
 
 root_path="/data"
-log_path="$root_path/klogcat/"`date +%F`
+klogcat_path="$root_path/klogcat"
+log_path="$klogcat_path/"`date +%F`
 screencap_path="$log_path/screencap/"
 plain_text_mail="false"
-
-# mail stuff
-mailserver="74.208.5.15"
-mailfrom="fudong@mail.com"
-mailto="fudong@mail.com"
-someone="Fudong"
-product="Vision"
-subject="$someone's $product has issue"
 
 switch_channel()
 {
@@ -106,21 +99,9 @@ gtv_get_bdaddr()
 	cat /sys/devices/virtual/bluetooth/hci0/address > $log_path/bdaddr.txt
 }
 
-gtv_kmsg()
-{
-	echo `date +%F-%H-%M-%S` > $log_path/kmsg.txt
-	cat /proc/kmsg >>$log_path/kmsg.txt&
-}
-
 gtv_getprop()
 {
 	getprop > $log_path/getprop.txt
-}
-
-gtv_getevent()
-{
-	echo `date +%F-%H-%M-%S` > $log_path/getevent.txt
-	getevent -lt >> $log_path/getevent.txt&
 }
 
 gtv_getip()
@@ -142,13 +123,13 @@ gtv_bluetooth_status()
 
 gtv_pack_log()
 {
-	cd $root_path
-	busybox tar cvf klogcat.tar klogcat
+	cd $klogcat_path
+	busybox tar cvf klogcat.tar $log_path
 	busybox bzip2 -zvv klogcat.tar
 
 	# busybox stat -c "%s" klogcat.tar.bz2
 	# if attachment larger than 5 MB, script will send plain text mail
-	size=`busybox du -k /sdcard/klogcat.tar.bz2|busybox awk '{print $1}'`
+	size=`busybox du -k $klogcat_path/klogcat.tar.bz2|busybox awk '{print $1}'`
 	max_size=5*1024
 
 	if [[ $size -lt $max_size ]]; then
@@ -186,7 +167,7 @@ busybox_sendmail()
 	echo "" >> $log_path/mail.txt
 	cat $log_path/getprop.txt >> $log_path/mail.txt
 	cat $log_path/mail.txt | busybox sendmail -v -S $mailserver -f $mailfrom \
-		-au"fudong@mail.com" -ap"qwerty123" $mailto
+		-au"$username" -ap"$passwd" $mailto
 }
 
 # send plain text message using busybox sendmail applet
@@ -200,31 +181,69 @@ busybox_sendmail_with_attachment()
 	echo "###################################################################"
 
 	busybox makemime -a "Subject: $subject" \
-		-o $root_path/attachment \
-		$root_path/klogcat.tar.bz2
+		-o $klogcat_path/attachment \
+		$klogcat_path/klogcat.tar.bz2
 	busybox sendmail -v -S $mailserver -f $mailfrom \
-		-au"fudong@mail.com" -ap"qwerty123" \
-		$mailto < $root_path/attachment
+		-au"$username" -ap"$passwd" \
+		$mailto < $klogcat_path/attachment
 }
 
 # remove all the temp files
 gtv_cleanup()
 {
-	rm $root_path/klogcat.tar*
-	rm $root_path/attachment
+	rm $klogcat_path/klogcat.tar*
+	rm $klogcat_path/attachment
 
 	# remove outdated traces.txt
 	if [ -f /data/anr/traces.txt ]; then
 		rm /data/anr/traces.txt
 	fi
 
-	kill -15 `busybox pidof getevent`
+	pid=`busybox pidof getevent`
+	if [ $? -eq 0 ]; then
+		echo "killing getevent"
+		kill -15 $pid
+	else
+		# TODO: this message should goes to a error log file
+		echo "getevent already killed"
+	fi
+
+	pid=`busybox pidof logcat`
+	if [ $? -eq 0 ]; then
+		echo "killing logcat"
+		kill -15 $pid
+	else
+		# TODO: this message should goes to a error log file
+		echo "logcat already killed"
+	fi
+}
+
+# select mail server
+gtv_mail_server()
+{
+	if [ $1 = "yeah" ]; then
+		mailserver="123.58.177.132"	# smtp.yeah.net
+		mailfrom="googletv@yeah.net"
+		username="googletv"
+		passwd="qwerty123"
+	elif [ $1 = "mail" ]; then
+		mailserver="74.208.5.15"	# mail.com
+		mailfrom="fudong@mail.com"
+		username="fudong@mail.com"
+		passwd="qwerty123"
+	fi
+	echo "mail server $1 selected"
 }
 
 gtv_post_processing()
 {
 	# bluetooth hci log
-	cp $root_path/misc/bluedroid/btsnoop_hci.log $log_path/
+	if [ -f "$root_path/misc/bluedroid/btsnoop_hci.log" ]; then
+		cp $root_path/misc/bluedroid/btsnoop_hci.log $log_path/
+	else
+		# TODO: this message should goes to a error log file
+		echo "btsnoop file not found"
+	fi
 	cp $root_path/misc/bluedroid/bt_config.* $log_path/
 
 	# pack all the log file
@@ -233,8 +252,14 @@ gtv_post_processing()
 	# see if we can send mail to module owner
 	#gtv_internet_available
 
-	# send mail to module owner
+	gtv_mail_server yeah
 
+	mailto="fudong@mail.com"
+	someone="Fudong"
+	product="Vision"
+	subject="$someone's $product has issue"
+
+	# send mail to module owner
 	if [ $1 = "true" ]; then
 		echo "sending plain text mail"
 		busybox_sendmail
@@ -253,7 +278,6 @@ gtv_prepare()
 	if [ ! -d "$log_path" ]; then
 		mkdir -p $log_path
 	fi
-
 	echo "log directory: $log_path"
 	echo "screencap directory: $screencap_path"
 
@@ -288,16 +312,27 @@ gtv_bluetooth_log()
 	gtv_bluetooth_status
 }
 
-gtv_remote_log()
+gtv_common_log()
 {
+	# logcat
+	echo `date +%F-%H-%M-%S` > $log_path/logcat.txt
+	logcat -v time > $log_path/logcat.txt&
+
 	# getevent
-	gtv_getevent
+	echo `date +%F-%H-%M-%S` > $log_path/getevent.txt
+	getevent -lt >> $log_path/getevent.txt&
+
+	# kernel log
+	echo `date +%F-%H-%M-%S` > $log_path/kmsg.txt
+	cat /proc/kmsg >>$log_path/kmsg.txt&
 }
 
 main()
 {
+	gtv_prepare
+	gtv_common_log
 	gtv_post_processing plain_text_mail
-	#gtv_cleanup
+	gtv_cleanup
 }
 
 main
